version: '3.8'

services:
  postgres:
    image: postgres:14 
    container_name: postgres_container
    environment:
      POSTGRES_USER: souvik        
      POSTGRES_PASSWORD: souvik  
      POSTGRES_DB: email_service        
    ports:
      - "5432:5432"                     
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  app:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: nestjs_app
    environment:
      DATABASE_URL: postgres://souvik:souvik@postgres:5432/email_service
    ports:
      - "3000:3000"                   
    depends_on:
      - postgres                      

volumes:
  postgres_data:
